# Generated by Django 5.1.5 on 2025-01-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('belligerent_1', models.CharField(max_length=200)),
                ('belligerent_2', models.CharField(max_length=200)),
                ('summary_1', models.TextField()),
                ('summary_2', models.TextField()),
                ('winner', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
