# Generated by Django 5.1.5 on 2025-01-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_debate_analysis_debate_evaluation_debate_judgment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt_name', models.CharField(max_length=100)),
                ('prompt_text', models.TextField()),
                ('response', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_interactions', to='debate.debate')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
