# Generated by Django 5.1.5 on 2025-01-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0008_debate_evaluation_formatted_and_more'),
        ('debate', 'XXXX_add_ip_credit_usage'),
    ]

    operations = [
    ]
