# Generated by Django 5.1.5 on 2025-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_merge_20250130_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcreditusage',
            name='ip_address',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
